version: "3.8"
services:
  db:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "user"
    restart: always
    networks:
      - backend
  service:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:8080
    volumes:
      - .:/app
    working_dir: /app/application
    environment:
      DB_URL: "customerdb"
      DB_USERNAME: "user"
    command: "mvn spring-boot:run"
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
